### ISSUE TITLE
Function to import ZTF schedule sim output

### ISSUE THREAD

**Issue by MickaelRigault** [MickaelRigault/simsurvey#1]
**moved from astrobject following the simulation schism**

The ZTF schedule simulator will use the LSST OpSIM format: https://confluence.lsstcorp.org/display/SIM/Summary+Table+Column+Descriptions
It should be straight-forward to write a function that imports this.

**Comment by ufeindt** [comment]
Basic function added but still need to convert data into the correct units. Not loading whole table for now, Need to think about what else to load.

Mickael, can we skype tomorrow?

**Comment by MickaelRigault** [comment]
sure, let's do that. would 10am work for you ?

**Comment by ufeindt** [comment]
Sure, that should work.

On 8 May 2016 16:37:50 CEST, Mickael Rigault <notifications@github.com> wrote:
>sure, let's do that. would 10am work for you ?
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MickaelRigault/simsurvey/issues/1#issuecomment-217723628

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
